import PageHero from "@/components/PageHero";import Reveal from "@/components/Reveal";import ContactForm from "@/components/ContactForm";import {contact} from "@/lib/data";
const hotelMap="https://www.google.com/maps?q="+encodeURIComponent("38/40 Olatunji Idowu Street, Ago Palace Way, Okota, Lagos, Nigeria")+"&output=embed";
const eventsMap="https://www.google.com/maps?q="+encodeURIComponent("187 Abaranje Road, Asalu Bus Stop, Ikotun, Alimosho, Lagos, Nigeria")+"&output=embed";
export default function Contact(){return <><PageHero eyebrow="Contact Royal Rex" title="Let us make your visit effortless." text="Reservations, celebrations and enquiries — our team is ready to help." image="https://images.unsplash.com/photo-1564501049412-61c2a3083791?auto=format&fit=crop&w=2400&q=90"/>
<section className="theme-surface contact-intro"><div className="shell"><Reveal><div className="contact-intro-grid"><div><p className="eyebrow">We are here for you</p><h2 className="display">Plan your stay.<br/><i>Start a conversation.</i></h2></div><p className="theme-muted">Whether you are planning a stay, celebration, spa visit or simply have a question, reach out to Royal Rex and let the team help make the details effortless.</p></div></Reveal></div></section>
<section className="theme-surface pb-28 md:pb-40"><div className="shell"><ContactForm/></div></section>
<section className="location-section"><div className="shell"><Reveal><div className="location-heading"><div><p className="eyebrow">Find Royal Rex</p><h2 className="display">Two Lagos destinations.<br/><i>One royal welcome.</i></h2></div><p>Explore our locations below and open your preferred destination directly in Google Maps for directions.</p></div></Reveal>
<div className="location-grid"><div className="location-card"><div className="map-frame"><iframe src={hotelMap} title="Royal Rex Hotels and Spa Okota location" loading="lazy" referrerPolicy="no-referrer-when-downgrade" allowFullScreen/></div><div className="location-info"><p className="eyebrow">Hotel & Spa · Okota</p><h3 className="display">Royal Rex Hotels & Spa</h3><p>{contact.hotel}</p><div className="location-actions">{contact.phones.map(p=><a key={p} href={"tel:+234"+p.slice(1)}>{p}</a>)}<a target="_blank" rel="noopener noreferrer" href={"https://www.google.com/maps/search/?api=1&query="+encodeURIComponent(contact.hotel)}>Get directions ↗</a></div></div></div>
<div className="location-card"><div className="map-frame"><iframe src={eventsMap} title="Royal Rex Events and Spa Ikotun location" loading="lazy" referrerPolicy="no-referrer-when-downgrade" allowFullScreen/></div><div className="location-info"><p className="eyebrow">Events & Spa · Ikotun</p><h3 className="display">Royal Rex Events & Spa</h3><p>{contact.events}</p><div className="location-actions"><a href={"tel:+234"+contact.eventsPhone.slice(1)}>{contact.eventsPhone}</a><a target="_blank" rel="noopener noreferrer" href={"https://www.google.com/maps/search/?api=1&query="+encodeURIComponent(contact.events)}>Get directions ↗</a></div></div></div></div></div></section>
<section className="theme-surface contact-direct"><div className="shell"><Reveal><div><p className="eyebrow">Prefer to speak directly?</p><h2 className="display">We’re only a call<br/>or message away.</h2></div><div><a className="contact-big-link" href={"mailto:"+contact.email}>{contact.email}<span>↗</span></a>{contact.phones.map(p=><a className="contact-big-link" key={p} href={"tel:+234"+p.slice(1)}>{p}<span>↗</span></a>)}</div></Reveal></div></section></>}