"use client";
import Link from "next/link";
import {motion} from "framer-motion";
import {Wifi,Snowflake,Tv,ShowerHead,Refrigerator,Users,BedDouble,Maximize2,UtensilsCrossed,ShieldCheck,ArrowRight} from "lucide-react";

const amenityIcons:any={wifi:Wifi,air:Snowflake,tv:Tv,shower:ShowerHead,fridge:Refrigerator,kitchen:UtensilsCrossed};
const details:any={
 standard:{subtitle:"A calm, considered retreat",description:"Settle into an intimate room shaped around uncomplicated comfort — ideal for a restful Lagos stay.",facts:[["20–25m²","Room size","size"],["2","Guests","guests"],["1","Royal bed","bed"]],amenities:[["wifi","Complimentary high-speed Wi-Fi"],["air","Air conditioning"],["tv","Cable TV / DSTV"],["shower","Private shower"],["fridge","In-room refrigerator"],["kitchen","Room service"]]},
 classic:{subtitle:"More room to settle in",description:"An elevated everyday stay with generous proportions and thoughtful essentials for work, rest and everything between.",facts:[["25–30m²","Room size","size"],["2","Guests","guests"],["1","Royal bed","bed"]],amenities:[["wifi","Complimentary high-speed Wi-Fi"],["air","Air conditioning"],["tv","Cable TV / DSTV"],["shower","Private shower"],["fridge","In-room refrigerator"],["kitchen","Room service"]]},
 royal:{subtitle:"Our signature room experience",description:"More space, considered details and an elevated sense of comfort create a stay worthy of the Royal Rex name.",facts:[["30–35m²","Room size","size"],["3","Guests","guests"],["1","Royal bed","bed"]],amenities:[["wifi","Complimentary high-speed Wi-Fi"],["air","Air conditioning"],["tv","Cable TV / DSTV"],["shower","Private shower"],["fridge","In-room refrigerator"],["kitchen","Tea service & room service"]]},
 apartment:{subtitle:"Space for longer, richer stays",description:"A private two-bedroom setting designed for families and longer visits, pairing the independence of an apartment with Royal Rex hospitality.",facts:[["2","Bedrooms","bed"],["4","Guests","guests"],["Private","Apartment","size"]],amenities:[["wifi","Complimentary high-speed Wi-Fi"],["air","Air conditioning"],["tv","Smart TV / entertainment"],["shower","Private bathroom facilities"],["fridge","Fridge / freezer"],["kitchen","Serviced kitchen"]],terms:["Refundable caution fee may apply","No ironing in the apartment","No laundry in the apartment","No cooking in the apartment","Towels and bathrobes provided"]}
};
function FactIcon({type}:{type:string}){const I=type==="guests"?Users:type==="bed"?BedDouble:Maximize2;return <I size={22} strokeWidth={1.5}/>}

export default function RoomExperience({room}:{room:any}){
 const d=details[room.slug]||details.standard;
 return <main className="room-detail-v2">
  <section className="rd-hero"><motion.img src={room.image} alt={room.name} initial={{scale:1.08}} animate={{scale:1}} transition={{duration:1.4,ease:[.2,.8,.2,1]}}/><div className="rd-hero-shade"/><div className="shell rd-hero-copy"><motion.div initial={{opacity:0,y:35}} animate={{opacity:1,y:0}} transition={{duration:.8,delay:.15}}><p className="eyebrow">Royal Rex · Stay</p><h1 className="display">{room.name}</h1><p>{d.subtitle}</p></motion.div><div className="rd-rate"><small>From</small><strong>{room.price}</strong><small>per night</small></div></div></section>
  <section className="rd-intro theme-surface"><div className="shell"><div className="rd-facts">{d.facts.map((x:any,i:number)=><motion.div key={x[1]} initial={{opacity:0,y:18}} whileInView={{opacity:1,y:0}} viewport={{once:true}} transition={{delay:i*.08}}><FactIcon type={x[2]}/><span><strong>{x[0]}</strong><small>{x[1]}</small></span></motion.div>)}</div><div className="rd-story"><div><p className="eyebrow">Your room</p><h2 className="display">Make yourself<br/><i>at home.</i></h2></div><p>{d.description}</p></div></div></section>
  <section className="rd-amenities"><div className="shell"><div className="rd-section-head"><div><p className="eyebrow">Everything you need</p><h2 className="display">Room <i>amenities.</i></h2></div><p>Thoughtful essentials are included to make your time at Royal Rex comfortable from arrival to departure.</p></div><div className="rd-amenity-grid">{d.amenities.map((a:any,i:number)=>{const I=amenityIcons[a[0]];return <motion.div className="rd-amenity" key={a[1]} initial={{opacity:0,y:25}} whileInView={{opacity:1,y:0}} viewport={{once:true,amount:.2}} transition={{delay:i*.055}}><I size={27} strokeWidth={1.35}/><span>{a[1]}</span></motion.div>})}</div></div></section>
  {d.terms&&<section className="rd-terms theme-surface"><div className="shell rd-terms-inner"><div><p className="eyebrow">Good to know</p><h2 className="display">Apartment<br/><i>guidelines.</i></h2></div><div>{d.terms.map((t:string,i:number)=><motion.p key={t} initial={{opacity:0,x:15}} whileInView={{opacity:1,x:0}} viewport={{once:true}} transition={{delay:i*.05}}><span>0{i+1}</span>{t}</motion.p>)}</div></div></section>}
  <section className="rd-reserve"><div className="shell rd-reserve-grid"><div><p className="eyebrow">Direct booking</p><h2 className="display">Your room is<br/><i>waiting.</i></h2><p>Reserve directly with Royal Rex for a simple, personal booking experience.</p><div className="rd-trust"><ShieldCheck size={18}/><span>Book directly with the hotel</span></div></div><div className="rd-book-card"><div className="rd-book-price"><span>From</span><strong>{room.price}</strong><small>/ night</small></div><div className="rd-book-summary"><span>{room.name}</span><span>{room.guests}</span></div><Link href={"/booking?room="+room.slug} className="rd-book-btn">Check availability <ArrowRight size={17}/></Link><a href="tel:+2349032691381" className="rd-call">Prefer to speak with us? <b>Call reservations</b></a></div></div></section>
 </main>
}